server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/amazon
      database: amazon

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
  file:
    report: src/test/resources/test_report.json
  fixedRate:
    in:
      milliseconds: 60000
  initialDelay:
    in:
      milliseconds: 30000